version: '3.4'

services:
  risecontact:
    image: ${DOCKER_REGISTRY-}risecontact
    build:
      context: .
      dockerfile: Rise.Contact/Dockerfile

  risereport:
    image: ${DOCKER_REGISTRY-}risereport
    build:
      context: .
      dockerfile: Rise.Report/Dockerfile

